### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by DapengFeng** [ori-drs/oxford_spires_dataset#18]
Hi @YifuTao. 

I am writing to seek your assistance with downloading the dataset you have shared via Google Drive. I encountered a problem while attempting to download the dataset as a single zip file, which resulted in a failure. The system suggests downloading each file individually, but this process seems quite cumbersome and time-consuming for me.

I was wondering if you could offer any alternative solutions or suggestions for downloading the dataset more efficiently. Your guidance would be greatly appreciated.

Thank you for your understanding and support.

![Screenshot from 2024-11-24 09-45-49](https://github.com/user-attachments/assets/d143509d-0c46-487a-8705-83aec928f7b0)

**Comment by YifuTao** [comment]
Hi Dapeng,

- It is difficult to zip the whole folder for a large mission since the total size is generally >20GB. It's better to separately download the large files in the `raw` folder such as rosbags. The `processed` folder will be smaller (except for COLMAP) and you probably can just download it. 
 - Some missions are larger than others. Keble-1 is larger than e.g. Keble-2.
 - For ease of downloading, we are planning to add a Hugging Face release and a script to download a whole folder automatically.

**Comment by YifuTao** [comment]
@DapengFeng, I have uploaded the dataset to [Hugging Face](https://huggingface.co/datasets/ori-drs/oxford_spires_dataset/tree/main).

You should be able to download the dataset with a simple Python script like this:
```python
from huggingface_hub import snapshot_download

example_pattern = "sequences/2024-03-12-keble-college-02/*"
snapshot_download(
    repo_id="ori-drs/oxford_spires_dataset",
    allow_patterns=example_pattern,
    local_dir=<your-local-dir>,
    repo_type="dataset",
)
```
